task:
  title: Is this a cat?
dataset:
  directory: dataset/image_classification/
  data_type: images
  judgements_file: outputs/image_classification/labels.csv
label:
  type: binary
model:
  directory: outputs/image_classification/models/
user: chris
