task:
  title: Label this sequence with its NERs
dataset:
  directory: dataset/sequence_labelling/
  data_type: text
  judgements_file: outputs/sequence_labelling/labels.csv
label:
  type: sequence
  valid_tokens:
    - O
    - B-TIME
    - I-TIME
    - B-LOC
    - I-LOC
    - B-PRI
    - I-PRI
model_directory: outputs/sequence_labelling/models/
user: chris
